# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget leptonica)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target leptonica
add_library(leptonica SHARED IMPORTED)

# Import target "leptonica" for configuration "Debug"
set_property(TARGET leptonica APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(leptonica PROPERTIES
  IMPORTED_IMPLIB_DEBUG "F:/Test/OcrDemo/leptonica-1.74.0/vs/src/Debug/leptonica-1.74.0d.lib"
  IMPORTED_LOCATION_DEBUG "F:/Test/OcrDemo/leptonica-1.74.0/vs/bin/Debug/leptonica-1.74.0d.dll"
  )

# Import target "leptonica" for configuration "Release"
set_property(TARGET leptonica APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(leptonica PROPERTIES
  IMPORTED_IMPLIB_RELEASE "F:/Test/OcrDemo/leptonica-1.74.0/vs/src/Release/leptonica-1.74.0.lib"
  IMPORTED_LOCATION_RELEASE "F:/Test/OcrDemo/leptonica-1.74.0/vs/bin/Release/leptonica-1.74.0.dll"
  )

# Import target "leptonica" for configuration "MinSizeRel"
set_property(TARGET leptonica APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(leptonica PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "F:/Test/OcrDemo/leptonica-1.74.0/vs/src/MinSizeRel/leptonica-1.74.0.lib"
  IMPORTED_LOCATION_MINSIZEREL "F:/Test/OcrDemo/leptonica-1.74.0/vs/bin/MinSizeRel/leptonica-1.74.0.dll"
  )

# Import target "leptonica" for configuration "RelWithDebInfo"
set_property(TARGET leptonica APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(leptonica PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "F:/Test/OcrDemo/leptonica-1.74.0/vs/src/RelWithDebInfo/leptonica-1.74.0.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "F:/Test/OcrDemo/leptonica-1.74.0/vs/bin/RelWithDebInfo/leptonica-1.74.0.dll"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
